const plans = {
  free: {
    name: 'Free Trial',
    price: 0,
    applications: 10,
    duration: '7 days',
    features: [
      '10 job applications',
      'Basic application tracking',
      'Email updates',
    ],
    interviewGuarantee: false,
  },
  starter: {
    name: 'Starter',
    price: 499,
    applications: 200,
    duration: '30 days',
    features: [
      '200 job applications',
      'Naukri + Indeed',
      'Weekly PDF report',
      'Application tracking sheet',
      'Email updates',
    ],
    interviewGuarantee: false,
  },
  pro: {
    name: 'Pro',
    price: 999,
    applications: 500,
    duration: '30 days',
    features: [
      '500 job applications',
      'Naukri + LinkedIn + Indeed',
      'Custom cover letter per job',
      'Weekly PDF + Excel report',
      'WhatsApp updates',
      'Resume refresh on all portals',
      'Priority worker assignment',
    ],
    interviewGuarantee: true,
    guaranteeText: '10 interview calls in 30 days or next month free',
  },
  max: {
    name: 'Max',
    price: 1999,
    applications: 1000,
    duration: '30 days',
    features: [
      '1000 job applications',
      'All portals (Naukri + LinkedIn + Indeed + Internshala + Freshersworld)',
      'Custom cover letter per job',
      'Daily PDF + Excel report',
      'WhatsApp updates + voice note summary',
      'Resume rewrite & optimization',
      'LinkedIn profile optimization',
      'Dedicated worker',
      'Priority SLA — applications start within 2 hours',
    ],
    interviewGuarantee: true,
    guaranteeText: '20 interview calls in 30 days or next month free',
  },
  mega: {
    name: 'Mega',
    price: 2499,
    applications: 2500,
    duration: '90 days',
    features: [
      '2500+ job applications over 3 months',
      'All portals (Naukri + LinkedIn + Indeed + Internshala + Freshersworld)',
      'Custom cover letter per job',
      'Daily PDF + Excel report',
      'WhatsApp updates + voice note summary',
      'Resume rewrite & optimization',
      'LinkedIn profile optimization',
      'Dedicated worker team',
      'Priority SLA — applications start within 1 hour',
      'Quarterly performance review call',
      'Save ₹3,500 vs monthly Max plan',
    ],
    interviewGuarantee: true,
    guaranteeText: '30 interview calls in 90 days or next quarter free',
  },
};

module.exports = plans;
