services:
  - type: web
    name: taskdone-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
