const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateProofPdf = async (task, workerName) => {
  const outputDir = path.join(__dirname, '..', 'uploads', `task-${task._id}`);
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const pdfPath = path.join(outputDir, 'proof-report.pdf');

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);

    doc.fontSize(24).font('Helvetica-Bold').text('TaskDone', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Task Completion Proof Report', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#10B981');
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').text('Task Details');
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica');
    doc.text(`Task ID: ${task._id}`);
    doc.text(`Title: ${task.title}`);
    doc.text(`Type: ${task.type}`);
    doc.text(`Status: ${task.status}`);
    doc.text(`Worker: ${workerName || 'N/A'}`);
    doc.text(`Created: ${task.createdAt}`);
    doc.text(`Completed: ${task.completedAt || 'N/A'}`);
    doc.moveDown();

    if (task.description) {
      doc.fontSize(12).font('Helvetica-Bold').text('Description');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica').text(task.description);
      doc.moveDown();
    }

    doc.fontSize(14).font('Helvetica-Bold').text('Execution Steps');
    doc.moveDown(0.5);

    if (task.steps?.length > 0) {
      task.steps.forEach((step, i) => {
        doc.fontSize(10).font('Helvetica-Bold').text(`Step ${i + 1}: ${step.action}`);
        if (step.note) doc.fontSize(9).font('Helvetica').text(step.note);
        if (step.screenshots?.length > 0) {
          step.screenshots.forEach(ss => {
            const ssPath = path.join(__dirname, '..', ss);
            if (fs.existsSync(ssPath)) {
              try { doc.image(ssPath, { width: 450 }); } catch (e) { doc.text(`[Screenshot: ${ss}]`); }
            }
          });
        }
        doc.moveDown();
      });
    } else {
      doc.fontSize(10).font('Helvetica').text('No steps recorded.');
    }

    if (task.workerNotes) {
      doc.moveDown();
      doc.fontSize(12).font('Helvetica-Bold').text('Worker Notes');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica').text(task.workerNotes);
    }

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#10B981');
    doc.moveDown(0.5);
    doc.fontSize(8).font('Helvetica').fillColor('#666')
      .text(`Generated by TaskDone on ${new Date().toISOString()}`, { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(`/uploads/task-${task._id}/proof-report.pdf`));
    stream.on('error', reject);
  });
};

module.exports = { generateProofPdf };
